services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - "3320:3306"
            